-- ─── 可列举选项数据 ──────────────────────────────────────────
-- 供 CommandDefs.GetOptions(optionsKey) 通过字符串 key 动态查找

local EnumOptions = {}

-- Challenge 选项 (45 items + clear)
EnumOptions.ChallengeOptions = {
    { value = "0",  label = "0: Clear" },
    { value = "1",  label = "1: Pitch Black" },
    { value = "2",  label = "2: High Brow" },
    { value = "3",  label = "3: Head Trauma" },
    { value = "4",  label = "4: Darkness Falls" },
    { value = "5",  label = "5: The Tank" },
    { value = "6",  label = "6: Solar System" },
    { value = "7",  label = "7: Suicide King" },
    { value = "8",  label = "8: Cat Got Your Tongue" },
    { value = "9",  label = "9: Demo Man" },
    { value = "10", label = "10: Cursed!" },
    { value = "11", label = "11: Glass Cannon" },
    { value = "12", label = "12: When Life Gives You Lemons" },
    { value = "13", label = "13: BEANS!" },
    { value = "14", label = "14: Its In The Cards" },
    { value = "15", label = "15: Slow Roll" },
    { value = "16", label = "16: Computer Savy" },
    { value = "17", label = "17: WAKA WAKA" },
    { value = "18", label = "18: The Host" },
    { value = "19", label = "19: The Family Man" },
    { value = "20", label = "20: Purist" },
    { value = "21", label = "21: XXXXXXXXL" },
    { value = "22", label = "22: SPEED!" },
    { value = "23", label = "23: Blue Bomber" },
    { value = "24", label = "24: PAY TO PLAY" },
    { value = "25", label = "25: Have a heart" },
    { value = "26", label = "26: I RULE!" },
    { value = "27", label = "27: BRAINS!" },
    { value = "28", label = "28: PRIDE DAY!" },
    { value = "29", label = "29: Onan's Streak" },
    { value = "30", label = "30: The Guardian" },
    { value = "31", label = "31: Backasswards" },
    { value = "32", label = "32: Aprils fool" },
    { value = "33", label = "33: Pokey mans" },
    { value = "34", label = "34: Ultra hard" },
    { value = "35", label = "35: PONG" },
    { value = "36", label = "36: Scat Man" },
    { value = "37", label = "37: Bloody Mary" },
    { value = "38", label = "38: Baptism by Fire" },
    { value = "39", label = "39: Isaac's Awakening" },
    { value = "40", label = "40: Seeing Double" },
    { value = "41", label = "41: Pica Run" },
    { value = "42", label = "42: Hot Potato" },
    { value = "43", label = "43: Cantripped!" },
    { value = "44", label = "44: Red Redemption" },
    { value = "45", label = "45: Delete This" },
}

-- EasterEggs 选项 (SeedEffect enum)
EnumOptions.EasterEggOptions = {
    { value = "0",   label = "0: Clear All" },
    { value = "1",   label = "1: MOVEMENT_PITCH" },
    { value = "2",   label = "2: HEALTH_PITCH" },
    { value = "3",   label = "3: CAMO_ISAAC" },
    { value = "4",   label = "4: CAMO_ENEMIES" },
    { value = "5",   label = "5: CAMO_PICKUPS" },
    { value = "6",   label = "6: CAMO_EVERYTHING" },
    { value = "7",   label = "7: FART_SOUNDS" },
    { value = "8",   label = "8: OLD_TV" },
    { value = "9",   label = "9: DYSLEXIA" },
    { value = "10",  label = "10: NO_HUD" },
    { value = "11",  label = "11: PICKUPS_SLIDE" },
    { value = "12",  label = "12: CONTROLS_REVERSED" },
    { value = "13",  label = "13: ALL_CHAMPIONS" },
    { value = "14",  label = "14: INVISIBLE_ISAAC" },
    { value = "15",  label = "15: INVISIBLE_ENEMIES" },
    { value = "16",  label = "16: INFINITE_BASEMENT" },
    { value = "17",  label = "17: ALWAYS_CHARMED" },
    { value = "18",  label = "18: ALWAYS_CONFUSED" },
    { value = "19",  label = "19: ALWAYS_AFRAID" },
    { value = "20",  label = "20: ALWAYS_ALT_FEAR" },
    { value = "21",  label = "21: CHARMED_AND_AFRAID" },
    { value = "23",  label = "23: EXTRA_BLOOD" },
    { value = "24",  label = "24: POOP_TRAIL" },
    { value = "25",  label = "25: PACIFIST" },
    { value = "26",  label = "26: DAMAGE_WHEN_STOPPED" },
    { value = "27",  label = "27: DAMAGE_ON_INTERVAL" },
    { value = "28",  label = "28: DAMAGE_ON_TIME_LIMIT" },
    { value = "29",  label = "29: PILLS_NEVER_IDENTIFY" },
    { value = "30",  label = "30: MYSTERY_TAROT_CARDS" },
    { value = "32",  label = "32: ENEMIES_RESPAWN" },
    { value = "33",  label = "33: ITEMS_COST_MONEY" },
    { value = "35",  label = "35: BIG_HEAD" },
    { value = "36",  label = "36: SMALL_HEAD" },
    { value = "37",  label = "37: BLACK_ISAAC" },
    { value = "38",  label = "38: GLOWING_TEARS" },
    { value = "41",  label = "41: SLOW_MUSIC" },
    { value = "42",  label = "42: ULTRA_SLOW_MUSIC" },
    { value = "43",  label = "43: FAST_MUSIC" },
    { value = "44",  label = "44: ULTRA_FAST_MUSIC" },
    { value = "46",  label = "46: NO_FACE" },
    { value = "47",  label = "47: HIGH_DAMAGE" },
    { value = "48",  label = "48: MASSIVE_DAMAGE" },
    { value = "52",  label = "52: ICE_PHYSICS" },
    { value = "53",  label = "53: KAPPA" },
    { value = "54",  label = "54: CHRISTMAS" },
    { value = "55",  label = "55: KIDS_MODE" },
    { value = "56",  label = "56: PERM_CURSE_DARKNESS" },
    { value = "57",  label = "57: PERM_CURSE_LABYRINTH" },
    { value = "58",  label = "58: PERM_CURSE_LOST" },
    { value = "59",  label = "59: PERM_CURSE_UNKNOWN" },
    { value = "60",  label = "60: PERM_CURSE_MAZE" },
    { value = "61",  label = "61: PERM_CURSE_BLIND" },
    { value = "62",  label = "62: PERM_CURSE_CURSED" },
    { value = "63",  label = "63: PREV_CURSE_DARKNESS" },
    { value = "64",  label = "64: PREV_CURSE_LABYRINTH" },
    { value = "65",  label = "65: PREV_CURSE_LOST" },
    { value = "66",  label = "66: PREV_CURSE_UNKNOWN" },
    { value = "67",  label = "67: PREV_CURSE_MAZE" },
    { value = "68",  label = "68: PREV_CURSE_BLIND" },
    { value = "70",  label = "70: PREVENT_ALL_CURSES" },
    { value = "71",  label = "71: NO_BOSS_ROOM_EXITS" },
    { value = "72",  label = "72: PICKUPS_TIMEOUT" },
    { value = "73",  label = "73: INVINCIBLE" },
    { value = "74",  label = "74: SHOOT_IN_MOVE_DIR" },
    { value = "75",  label = "75: SHOOT_OPP_MOVE_DIR" },
    { value = "76",  label = "76: AXIS_ALIGNED_CTRL" },
    { value = "77",  label = "77: SUPER_HOT" },
    { value = "78",  label = "78: RETRO_VISION" },
    { value = "79",  label = "79: G_FUEL" },
}

-- TP 选项 (GridRooms enum, negative IDs for special rooms)
EnumOptions.TPOptions = {
    { value = "-1",  label = "-1: Devil" },
    { value = "-2",  label = "-2: Error" },
    { value = "-3",  label = "-3: Debug" },
    { value = "-4",  label = "-4: Dungeon" },
    { value = "-5",  label = "-5: BossRush" },
    { value = "-6",  label = "-6: BlackMarket" },
    { value = "-7",  label = "-7: MegaSatan" },
    { value = "-8",  label = "-8: BlueWomb" },
    { value = "-9",  label = "-9: TheVoid" },
    { value = "-10", label = "-10: SecretExit" },
    { value = "-11", label = "-11: GideonDungeon" },
    { value = "-12", label = "-12: Genesis" },
    { value = "-13", label = "-13: SecretShop" },
    { value = "-14", label = "-14: RotgutDungeon1" },
    { value = "-15", label = "-15: RotgutDungeon2" },
    { value = "-16", label = "-16: BlueRoom" },
    { value = "-17", label = "-17: ExtraBoss" },
    { value = "-18", label = "-18: AngelShop" },
    { value = "-19", label = "-19: Deathmatch" },
    { value = "-20", label = "-20: LilPortal" },
}

-- PlayerType 选项 (vanilla characters)
EnumOptions.PlayerTypeOptions = {
    { value = "0",  label = "0: Isaac" },
    { value = "1",  label = "1: Magdalene" },
    { value = "2",  label = "2: Cain" },
    { value = "3",  label = "3: Judas" },
    { value = "4",  label = "4: Blue Baby" },
    { value = "5",  label = "5: Eve" },
    { value = "6",  label = "6: Samson" },
    { value = "7",  label = "7: Azazel" },
    { value = "8",  label = "8: Lazarus" },
    { value = "9",  label = "9: Eden" },
    { value = "10", label = "10: The Lost" },
    { value = "11", label = "11: Lazarus II" },
    { value = "12", label = "12: Black Judas" },
    { value = "13", label = "13: Lilith" },
    { value = "14", label = "14: Keeper" },
    { value = "15", label = "15: Apollyon" },
    { value = "16", label = "16: The Forgotten" },
    { value = "17", label = "17: The Soul" },
    { value = "18", label = "18: Bethany" },
    { value = "19", label = "19: Jacob" },
    { value = "20", label = "20: Esau" },
    { value = "_isaac",       label = "T.Isaac" },
    { value = "_magdalene",   label = "T.Magdalene" },
    { value = "_cain",        label = "T.Cain" },
    { value = "_judas",       label = "T.Judas" },
    { value = "_bluebaby",    label = "T.Blue Baby" },
    { value = "_eve",         label = "T.Eve" },
    { value = "_samson",      label = "T.Samson" },
    { value = "_azazel",      label = "T.Azazel" },
    { value = "_lazarus",     label = "T.Lazarus" },
    { value = "_eden",        label = "T.Eden" },
    { value = "_thelost",     label = "T.Lost" },
    { value = "_lilith",      label = "T.Lilith" },
    { value = "_keeper",      label = "T.Keeper" },
    { value = "_apollyon",    label = "T.Apollyon" },
    { value = "_theforgotten",label = "T.Forgotten" },
    { value = "_bethany",     label = "T.Bethany" },
    { value = "_jacob",       label = "T.Jacob" },
}

return EnumOptions
